### PR TITLE
fix(bigtable): Update cbt import instructions to include .csv format …

### PR DESCRIPTION
**Pull request by markduffett**
…information

### CODE REVIEW

**Comment by markduffett** [comment]
@telpirion An update to the cbtdoc should go with this PR. I could do so in the original repo no problem and updated the PR there. However I could not run 'go generate' successfully here (build works fine).

$ go generate
# command-line-arguments
./cbt.go:50:23: undefined: Config
./cbt.go:165:21: undefined: Config
./cbt.go:273:13: undefined: RequiredFlags
./cbt.go:280:13: undefined: ProjectAndInstanceRequired
./cbt.go:294:13: undefined: ProjectRequired
./cbt.go:306:13: undefined: ProjectAndInstanceRequired
./cbt.go:314:13: undefined: ProjectAndInstanceRequired
./cbt.go:327:13: undefined: ProjectAndInstanceRequired
./cbt.go:337:13: undefined: ProjectAndInstanceRequired
./cbt.go:345:13: undefined: ProjectRequired
./cbt.go:345:13: too many errors
cbt.go:952: running "go": exit status 2
$ go build
$

**Review by billyjacobson — APPROVED** [review]

**Comment by telpirion** [comment]
> @telpirion An update to the cbtdoc should go with this PR. I could do so in the original repo no problem and updated the PR there. However I could not run 'go generate' successfully here (build works fine).
> 
> ```
> $ go generate
> # command-line-arguments
> ./cbt.go:50:23: undefined: Config
> ./cbt.go:165:21: undefined: Config
> ./cbt.go:273:13: undefined: RequiredFlags
> ./cbt.go:280:13: undefined: ProjectAndInstanceRequired
> ./cbt.go:294:13: undefined: ProjectRequired
> ./cbt.go:306:13: undefined: ProjectAndInstanceRequired
> ./cbt.go:314:13: undefined: ProjectAndInstanceRequired
> ./cbt.go:327:13: undefined: ProjectAndInstanceRequired
> ./cbt.go:337:13: undefined: ProjectAndInstanceRequired
> ./cbt.go:345:13: undefined: ProjectRequired
> ./cbt.go:345:13: too many errors
> cbt.go:952: running "go": exit status 2
> $ go build
> $
> ```

This is fixed in #17

**Review by telpirion — APPROVED** [review]
This looks good. Let's hold off on merging until I have the presubmits & CI/CD hooked up. Thanks!

**Comment by telpirion** [comment]
This is now ready to merge! Please be sure to merge any additional updates to main and make sure the presubmits are green.

**Comment by markduffett** [comment]
@telpirion Thanks, I do not have write privileges to this repo (no merge button). I have no new changes. Feel free to merge.

**Pull request merged**
